# Generated by Django 6.1.1 on 2026-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='image')),
                ('category', models.CharField(choices=[('annonce', 'Annonce'), ('formation', 'Formation'), ('evenement', 'Événement'), ('publicite', 'Publicité')], default='annonce', max_length=20, verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'actualité',
                'verbose_name_plural': 'actualités',
                'ordering': ['-published_date', '-pk'],
            },
        ),
    ]
