# Generated by Django 6.1.1 on 2026-10-09 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='abonné')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='adresse confirmée')),
                ('consented_at', models.DateTimeField(auto_now_add=True, verbose_name='consentement donné le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='adresse confirmée le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='désinscrit le')),
            ],
            options={
                'verbose_name': 'abonné à la newsletter',
                'verbose_name_plural': 'abonnés à la newsletter',
                'ordering': ['-consented_at', '-pk'],
            },
        ),
    ]
