# Generated by Django 6.1.1 on 2026-10-09 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('body', models.CharField(max_length=500, verbose_name='message')),
                ('target_url', models.CharField(default='/', max_length=2048, verbose_name='page à ouvrir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyée le')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='envois acceptés')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='échecs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_push_notifications', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire (vide : tous les appareils)')),
            ],
            options={
                'verbose_name': 'notification push',
                'verbose_name_plural': 'notifications push',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048, unique=True, verbose_name='point de livraison push')),
                ('p256dh', models.CharField(max_length=255, verbose_name='clé publique de chiffrement')),
                ('auth', models.CharField(max_length=255, verbose_name='secret de chiffrement')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='navigateur et appareil')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrit le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'appareil avec notifications push',
                'verbose_name_plural': 'appareils avec notifications push',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
