# Generated by Django 6.1.1 on 2026-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='formation_images/', verbose_name='image')),
                ('category', models.CharField(choices=[('developpement', 'Développement'), ('ia', 'Intelligence artificielle'), ('design', 'Design'), ('autres', 'Autres')], default='autres', max_length=20, verbose_name='catégorie')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='durée')),
                ('level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous', 'Tous niveaux')], default='debutant', max_length=20, verbose_name='niveau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
