# Generated by Django 6.1.1 on 2026-10-09 09:13

import django.core.validators
import django.db.models.deletion
import formations.storage
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide pour un nombre de places illimité.', null=True, verbose_name='nombre de places'),
        ),
        migrations.AddField(
            model_name='formation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3, verbose_name='devise'),
        ),
        migrations.AddField(
            model_name='formation',
            name='delivery_mode',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'En présentiel'), ('hybride', 'Hybride')], default='en_ligne', max_length=20, verbose_name='format'),
        ),
        migrations.AddField(
            model_name='formation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AddField(
            model_name='formation',
            name='instructor',
            field=models.CharField(blank=True, max_length=200, verbose_name='formateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='lieu ou lien de formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix'),
        ),
        migrations.AddField(
            model_name='formation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de début'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='téléphone / WhatsApp')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('liste_attente', "Liste d'attente"), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de demande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='formations.formation', verbose_name='formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='apprenant')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='numéro de vérification')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='date de délivrance')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='formations.enrollment', verbose_name='inscription')),
            ],
            options={
                'verbose_name': 'attestation',
                'verbose_name_plural': 'attestations',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='résumé')),
                ('content', models.TextField(blank=True, verbose_name='contenu')),
                ('video_url', models.URLField(blank=True, verbose_name='lien vidéo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='formations.formation', verbose_name='formation')),
            ],
            options={
                'verbose_name': 'leçon',
                'verbose_name_plural': 'leçons',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='terminée')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='formations.lesson', verbose_name='leçon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='apprenant')),
            ],
            options={
                'verbose_name': 'progression de leçon',
                'verbose_name_plural': 'progressions de leçon',
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('file', models.FileField(blank=True, storage=formations.storage.PrivateMediaStorage(), upload_to='protected_resources/', verbose_name='fichier')),
                ('external_url', models.URLField(blank=True, verbose_name='lien externe')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='formations.lesson', verbose_name='leçon')),
            ],
            options={
                'verbose_name': 'ressource de leçon',
                'verbose_name_plural': 'ressources de leçon',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='devise')),
                ('provider', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('mpesa', 'M-Pesa'), ('afrimoney', 'Afrimoney'), ('autre', 'Autre')], max_length=20, verbose_name='opérateur')),
                ('transaction_reference', models.CharField(max_length=128, verbose_name='référence de transaction')),
                ('proof', models.ImageField(blank=True, storage=formations.storage.PrivateMediaStorage(), upload_to='payment_proofs/', verbose_name='preuve de paiement')),
                ('status', models.CharField(choices=[('en_attente', 'À vérifier'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=12, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de soumission')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de vérification')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='formations.enrollment', verbose_name='inscription')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='vérifié par')),
            ],
            options={
                'verbose_name': 'paiement Mobile Money',
                'verbose_name_plural': 'paiements Mobile Money',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'formation'), name='unique_student_formation'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_student_lesson_progress'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference', ''), _negated=True), fields=('transaction_reference',), name='unique_mobile_money_reference'),
        ),
    ]
